import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { colors, themes } from "../../colors.ts";
import { easings } from "../../easings.ts";
import { breakpoints, customSizes, layout, screens } from "../../layout.ts";
import { fonts, typography } from "../../typography.ts";
import { generateMedia } from "../generate-media.ts";
import { generateRoot } from "../generate-root.ts";
import { generateScale } from "../generate-scale.ts";
import { generateTailwind } from "../generate-tailwind.ts";

interface DarkroomStylingOptions {
  prependCss?: string;
  watchFiles?: string[];
}

const defaults: Required<DarkroomStylingOptions> = {
  prependCss: "./styles/css/media.css",
  watchFiles: [
    "styles/colors.ts",
    "styles/typography.ts",
    "styles/easings.ts",
    "styles/layout.ts",
  ],
};

const banner = `/*
 * THIS FILE IS GENERATED BY darkroom-styling vite plugin
 * DO NOT EDIT IT DIRECTLY.
 */`;

function generate() {
  const tw = generateTailwind({ breakpoints, colors, customSizes, easings, fonts, themes, typography });
  const root = generateRoot({ colors, customSizes, easings, layout, screens });
  const scale = generateScale();
  const media = generateMedia({ breakpoints });

  writeFileSync("./styles/css/tailwind.css", [banner, tw, scale].join("\n\n"));
  writeFileSync("./styles/css/root.css", [banner, root].join("\n\n"));
  writeFileSync("./styles/css/media.css", [banner, media].join("\n\n"));

  console.log("✓ Style config generated");
}

export function darkroomStyling(options?: DarkroomStylingOptions): Plugin {
  const config = { ...defaults, ...options };
  const prependResolved = path.resolve(config.prependCss);

  return {
    name: "darkroom-styling",
    enforce: "pre",

    // Generate CSS files once before anything else
    configResolved() {
      generate();
    },

    // In dev: watch config files and regenerate on change
    configureServer(server) {
      server.watcher.add(config.watchFiles);
      server.watcher.on("change", (filePath) => {
        if (config.watchFiles.some((file) => filePath.includes(file))) {
          generate();
        }
      });
    },

    // Prepend @import for custom media queries into all CSS files
    transform(code, id) {
      if (!existsSync(prependResolved) || !id.endsWith(".css")) return;

      const parts = code.split("\n");
      let insertIndex = 0;

      for (const part of parts) {
        const trimmed = part.trim();
        if (trimmed.startsWith("@charset") || trimmed.startsWith("@layer")) {
          insertIndex++;
        } else {
          break;
        }
      }

      parts.splice(insertIndex, 0, `@import '${config.prependCss}';`);
      return parts.join("\n");
    },
  };
}
