import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { colors, themes } from "../../colors.ts";
import { easings } from "../../easings.ts";
import { breakpoints, customSizes, layout, screens } from "../../layout.ts";
import { fonts, typography } from "../../typography.ts";
import { generateMedia } from "../generate-media.ts";
import { generateRoot } from "../generate-root.ts";
import { generateScale } from "../generate-scale.ts";
import { generateTailwind } from "../generate-tailwind.ts";

interface DarkroomStylingOptions {
  /** CSS file to prepend into all CSS files (for custom media queries) */
  prependCss?: string;
  /** Style config files to watch for regeneration */
  watchFiles?: string[];
  /** Generated files that must exist before dev server starts */
  requiredFiles?: string[];
}

const defaults: Required<DarkroomStylingOptions> = {
  prependCss: "./styles/css/media.css",
  watchFiles: [
    "styles/colors.ts",
    "styles/typography.ts",
    "styles/easings.ts",
    "styles/layout.ts",
  ],
  requiredFiles: [
    "./styles/css/root.css",
    "./styles/css/tailwind.css",
    "./styles/css/media.css",
  ],
};

const banner = `/*
 * THIS FILE IS GENERATED BY darkroom-styling vite plugin
 * DO NOT EDIT IT DIRECTLY.
 */`;

function generate() {
  const tailwind = generateTailwind({ breakpoints, colors, customSizes, easings, fonts, themes, typography });
  const root = generateRoot({ colors, customSizes, easings, layout, screens });
  const scale = generateScale();
  const media = generateMedia({ breakpoints });

  writeFileSync("./styles/css/tailwind.css", [banner, tailwind, scale].join("\n\n"));
  writeFileSync("./styles/css/root.css", [banner, root].join("\n\n"));
  writeFileSync("./styles/css/media.css", [banner, media].join("\n\n"));

  console.log("✓ Style config generated");
}

export function darkroomStyling(options?: DarkroomStylingOptions): Plugin {
  const config = { ...defaults, ...options };

  const prependResolved = path.resolve(config.prependCss);
  const prependExists = existsSync(prependResolved);

  return {
    name: "darkroom-styling",
    enforce: "pre",

    // Generate on startup if files are missing, watch for changes
    configureServer(server) {
      const missing = config.requiredFiles.some((f) => !existsSync(f));
      if (missing) generate();

      server.watcher.add(config.watchFiles);
      server.watcher.on("change", (filePath) => {
        if (config.watchFiles.some((file) => filePath.includes(file))) {
          generate();
        }
      });
    },

    // Also generate at build time
    buildStart() {
      generate();
    },

    // Restart dev server when the prepended CSS changes
    handleHotUpdate({ file, server }) {
      if (file.includes(config.prependCss.replace(/^(\.\/|\.\.\/)+/, ""))) {
        void server.restart();
      }
    },

    // Prepend @import for custom media queries into all CSS files
    transform(code, id) {
      if (!prependExists || !id.endsWith(".css")) return;

      const parts = code.split("\n");
      let insertIndex = 0;

      for (const part of parts) {
        const trimmed = part.trim();
        if (trimmed.startsWith("@charset") || trimmed.startsWith("@layer")) {
          insertIndex++;
        } else {
          break;
        }
      }

      parts.splice(insertIndex, 0, `@import '${config.prependCss}';`);
      return parts.join("\n");
    },
  };
}
