/**
 * Component inventory template for the client handoff script.
 *
 * Pure render function -- no I/O. `prepare-handoff.ts` scans the filesystem for
 * components and pages, then passes the gathered lists here. A `null` list means
 * the corresponding scan failed and the section renders a fallback line.
 */

import type { IntegrationStatus } from './deployment-checklist'

export interface InventoryData {
  /** ISO date (YYYY-MM-DD) shown in the "Generated:" line. */
  date: string
  /** Integrations that ship on disk, each with its env-configured status. */
  integrations: IntegrationStatus[]
  /** Sorted `components/ui` names, or `null` if the scan failed. */
  uiComponents: string[] | null
  /** Sorted `components/layout` names, or `null` if the scan failed. */
  layoutComponents: string[] | null
  /** Sorted `components/effects` names, or `null` if the scan failed. */
  effectComponents: string[] | null
  /** Processed page routes (examples excluded), or `null` if the scan failed. */
  pages: string[] | null
}

/** Render a `## <heading>` section listing component names, or a fallback line. */
function pushComponentSection(
  lines: string[],
  heading: string,
  components: string[] | null,
  scanErrorLine: string
): void {
  lines.push(heading)
  lines.push('')
  if (components === null) {
    lines.push(scanErrorLine)
  } else {
    for (const name of components) {
      lines.push(`- \`${name}\``)
    }
  }
  lines.push('')
}

/** Render the component inventory markdown. */
export function renderInventory({
  date,
  integrations,
  uiComponents,
  layoutComponents,
  effectComponents,
  pages,
}: InventoryData): string {
  const lines: string[] = []

  lines.push('# Component Inventory')
  lines.push('')
  lines.push(`Generated: ${date}`)
  lines.push('')
  // P-C7: a later `setup:project` run (integration strip) can leave this
  // snapshot stale with no signal. Self-describe it instead of staying silent.
  lines.push(
    `> Snapshot generated by \`bun run handoff\` on ${date}. Regenerate after any later integration changes by re-running \`bun run handoff\`.`
  )
  lines.push('')

  lines.push('## Installed Integrations')
  lines.push('')
  if (integrations.length > 0) {
    for (const { name, configured } of integrations) {
      lines.push(
        configured ? `- ${name}` : `- ${name} — installed, needs configuration`
      )
    }
  } else {
    lines.push('- None installed')
  }
  lines.push('')

  pushComponentSection(
    lines,
    '## UI Components',
    uiComponents,
    '- Could not scan components'
  )
  pushComponentSection(
    lines,
    '## Layout Components',
    layoutComponents,
    '- Could not scan layout components'
  )
  pushComponentSection(
    lines,
    '## Effect Components',
    effectComponents,
    '- Could not scan effect components'
  )

  lines.push('## Pages')
  lines.push('')
  if (pages === null) {
    lines.push('- Could not scan pages')
  } else {
    for (const route of pages) {
      lines.push(`- \`/${route}\``)
    }
  }
  // Trailing blank line so the joined text ends in `\n`, matching
  // deployment-checklist.ts's pattern — a document without one fails
  // `oxfmt --check` (P-C2).
  lines.push('')

  return lines.join('\n')
}
