import * as config from '../config'
import { generateRoot } from './generate-root'
import { generateScale } from './generate-scale'
import { generateTailwind } from './generate-tailwind'

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

export const OUTPUTS = {
  tailwind: 'lib/styles/css/tailwind.css',
  root: 'lib/styles/css/root.css',
} as const

/**
 * Build the generated stylesheets in memory, without touching disk.
 *
 * Kept pure so `setup-styles.test.ts` can assert the committed CSS still
 * matches what the current palette and config produce.
 */
export function buildStyleSheets() {
  return {
    tailwind: [banner, generateTailwind(config), generateScale()].join('\n\n'),
    root: [banner, generateRoot(config)].join('\n\n'),
  }
}

if (import.meta.main) {
  const { tailwind, root } = buildStyleSheets()

  await Bun.write(`./${OUTPUTS.tailwind}`, tailwind)
  await Bun.write(`./${OUTPUTS.root}`, root)

  console.log(
    Bun.color('green', 'ansi'),
    '✓',
    Bun.color('black', 'ansi'),
    'Style config generated successfully'
  )
}
