import { defineConfig } from 'oxfmt'

/**
 * Oxfmt configuration.
 *
 * A `.ts` file rather than `.oxfmtrc.json` so `bun run typecheck` covers it.
 * Note the filename: oxfmt auto-discovers `oxfmt.config.ts`, NOT `.oxfmtrc.ts`.
 *
 * House style is unchanged from the Biome era: 80 columns, 2-space indent,
 * single quotes, semicolons only where required, es5 trailing commas, LF.
 * oxfmt's own defaults differ (printWidth 100, semi true, singleQuote false,
 * trailingComma "all"), so every one of those is set explicitly.
 */
export default defineConfig({
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  trailingComma: 'es5',
  arrowParens: 'always',
  endOfLine: 'lf',
  // Stops Markdown prose being re-wrapped, which keeps the .md diff to
  // whitespace and table normalisation instead of a full rewrite.
  proseWrap: 'preserve',

  // Both sorters are off by default and have to be switched on. Between them
  // they replace Biome's organizeImports assist action and the useSortedClasses
  // nursery lint rule, which is why unsorted classes are no longer a lint error.
  sortImports: {
    groups: [
      'builtin',
      'external',
      ['internal', 'subpath'],
      ['parent', 'sibling', 'index'],
      'style',
      'unknown',
    ],
    // A prefix list, not a regex. `["^@/.*"]` matches nothing and silently
    // lumps every @/ import in with the external packages.
    internalPattern: ['@/'],
    ignoreCase: true,
    // Keeps side-effect imports where they are. The `style` group above is what
    // holds app/layout.tsx's trailing `import '@/lib/styles/css/index.css'` at
    // the bottom of the block.
    sortSideEffects: false,
  },

  sortTailwindcss: {
    // Resolves the @theme tokens (custom `dt:` breakpoint, `primary` colour).
    stylesheet: './lib/styles/css/index.css',
    functions: ['cn', 'clsx'],
  },

  // sortPackageJson is on by default; this keeps the human-curated script order.
  sortPackageJson: {
    sortScripts: false,
  },

  ignorePatterns: [
    'node_modules/**',
    '.next/**',
    'dist/**',
    'public/**',
    '.vercel/**',
    'bun.lock',
    // Generated by `bun run setup:styles`, and tab-indented on purpose.
    // Formatting them puts the generator and the formatter in a permanent fight.
    'lib/styles/css/tailwind.css',
    'lib/styles/css/root.css',
    // Generated by `bun run sanity:typegen`.
    'lib/integrations/sanity/sanity.types.ts',
    // Vendored from dmmulroy/anti-slop; keeps upstream formatting so a
    // sync diff against upstream stays readable.
    'tools/oxlint/anti-slop/**',
    // Generated by `bun run generate:manifest`.
    'COMPONENTS.md',
    // Append-only; reflowing it destroys history readability.
    'CHANGELOG.md',
  ],
})
