import { defineConfig } from 'oxlint'

/**
 * Oxlint configuration.
 *
 * This is a `.ts` file rather than `.oxlintrc.json` so the config is covered by
 * `bun run typecheck` in CI. That catches invalid severities and duplicate rule
 * keys, both of which a JSON config accepts silently. Note the filename: oxlint
 * auto-discovers `oxlint.config.ts`, NOT `.oxlintrc.ts`. Get it wrong and it
 * falls back to defaults without saying anything.
 *
 * Rule names themselves are not typed (the rule map is a permissive
 * `Record<string, ...>`), so a typo'd rule name still slips through.
 */
export default defineConfig({
  jsPlugins: [
    { name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' },
  ],
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'react',
    'jsx-a11y',
    'nextjs',
    'import',
    'promise',
  ],
  categories: {
    correctness: 'error',
  },
  env: {
    browser: true,
    node: true,
    es2024: true,
  },

  // How the custom components are taught to the linter. `settings` is root-only;
  // it cannot be scoped in an overrides block.
  settings: {
    react: {
      // Makes react/jsx-no-target-blank check <Link target="_blank"> for a
      // missing rel. Belt-and-braces: components/ui/link strips any caller
      // target/rel and forces rel="noopener noreferrer" itself.
      //
      // The key is `attribute`, not eslint-plugin-react's `linkAttribute`.
      // oxlint ignores unknown keys, so the wrong spelling looks like it works.
      linkComponents: [{ name: 'Link', attribute: 'href' }],
    },
    'jsx-a11y': {
      components: {
        // Makes jsx-a11y/alt-text check our <Image> (and next/image) for a
        // missing alt. Verified: it fires on <Image src width height> with no
        // alt, and does NOT make nextjs/no-img-element flag <Image>.
        Image: 'img',

        // Deliberately NOT mapped:
        //
        // Link: 'a' would give us jsx-a11y/anchor-is-valid on <Link>, but
        // react/forbid-elements reads this same map, so every one of the 13
        // <Link> usages in the repo gets reported as a forbidden raw anchor.
        // Silencing those would gut the rule that replaced the old
        // no-anchor-element GritQL plugin. The only thing the mapping actually
        // catches here is <Link href="#">; the real risk (target/rel) is
        // covered above. Revisit if oxlint stops sharing the map across
        // plugins.
        //
        // SanityImage: 'img' reports a false positive: the component resolves
        // alt={alt ?? image.alt ?? ''} from CMS data, so call sites
        // legitimately omit it.
      },
    },
  },

  ignorePatterns: [
    '.next/**',
    'dist/**',
    'public/**',
    '.vercel/**',
    '.github/**',
    'storybook-static/**',
    'playwright-report/**',
    'test-results/**',
    'coverage/**',
    'next-env.d.ts',
    // Generated by `bun run sanity:typegen`. Linting it means --fix rewrites
    // generated output that the next typegen run reverts. oxfmt ignores it for
    // the same reason.
    'lib/integrations/sanity/sanity.types.ts',
    'tools/oxlint/anti-slop/**',
  ],

  rules: {
    // --- anti-slop (vendored, tools/oxlint/anti-slop) -------------------------
    // Rules that reject low-evidence TypeScript patterns, aimed at the code
    // agents tend to produce. Vendored per upstream's own recommendation
    // (https://github.com/dmmulroy/anti-slop), so the rules are ours to edit;
    // no-module-mocking is extended locally to recognize bun:test mock.module.
    // The Effect-specific plugin is not vendored; this repo does not use Effect.
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    // allowInTypeGuards keeps `typeof` legal inside named type-guard
    // functions. The remaining literal `typeof window` SSR guards carry
    // per-site disable comments instead of an isServer utility: Next
    // statically replaces literal `typeof window` in client bundles, so
    // extracting the check into a shared const would defeat dead-code
    // elimination of server-only branches.
    'anti-slop/no-runtime-typeof': ['error', { allowInTypeGuards: true }],
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',

    'eslint/no-unused-vars': [
      'error',
      {
        args: 'after-used',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      },
    ],
    'react/exhaustive-deps': 'warn',
    'eslint/no-use-before-define': [
      'error',
      { functions: false, classes: true, variables: true },
    ],
    'eslint/no-param-reassign': 'error',
    'typescript/prefer-as-const': 'error',
    'eslint/default-param-last': 'error',
    'typescript/prefer-enum-initializers': 'error',
    'react/self-closing-comp': ['error', { html: true, component: true }],
    'unicorn/prefer-number-properties': [
      'error',
      { checkInfinity: true, checkNaN: true },
    ],
    'typescript/no-inferrable-types': 'error',
    'eslint/no-else-return': ['error', { allowElseIf: false }],
    'typescript/array-type': ['error', { default: 'array', readonly: 'array' }],
    'typescript/prefer-for-of': 'warn',
    'eslint/operator-assignment': ['error', 'always'],
    'eslint/prefer-template': 'warn',
    'unicorn/no-lonely-if': 'warn',
    'eslint/prefer-exponentiation-operator': 'error',
    'unicorn/new-for-builtins': 'error',
    'unicorn/filename-case': [
      'warn',
      {
        cases: { kebabCase: true, camelCase: true },
        multipleFileExtensions: true,
      },
    ],
    'eslint/no-nested-ternary': 'error',
    'typescript/no-explicit-any': 'error',
    'eslint/no-empty': ['warn', { allowEmptyCatch: false }],
    'eslint/no-empty-function': 'warn',
    'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
    'eslint/no-debugger': 'warn',
    'eslint/no-misleading-character-class': 'error',
    'eslint/no-prototype-builtins': 'warn',
    'eslint/no-self-compare': 'error',
    'eslint/no-sparse-arrays': 'error',
    'eslint/no-unneeded-ternary': 'warn',
    'unicorn/prefer-array-flat-map': 'warn',
    'eslint/no-eval': 'error',
    'react/no-danger': 'warn',
    'react/no-danger-with-children': 'error',
    'jsx-a11y/click-events-have-key-events': 'warn',
    'jsx-a11y/anchor-is-valid': 'warn',
    'jsx-a11y/alt-text': 'error',
    'react/button-has-type': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/no-autofocus': 'warn',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/img-redundant-alt': 'error',
    // Maps to Biome's useSemanticElements, which was also a non-blocking warn.
    // 3 pre-existing `role="status"` live regions in the Shopify cart; swapping
    // them for <output> changes the rendered element and its styling, so it is
    // a deliberate follow-up rather than part of this migration.
    'jsx-a11y/prefer-tag-over-role': 'off',
    'nextjs/no-img-element': 'error',
    'import/first': 'error',
    'react/rules-of-hooks': 'error',
    'react/forbid-elements': [
      'error',
      {
        forbid: [
          {
            element: 'a',
            message:
              'Use the custom Link component (@/components/ui/link) instead of a raw anchor element. It handles internal and external links automatically.',
          },
        ],
      },
    ],
    'eslint/no-restricted-imports': [
      'error',
      {
        paths: [
          {
            name: 'react',
            importNames: ['forwardRef'],
            message:
              'forwardRef is unnecessary in React 19 with the compiler - accept `ref` as a regular prop.',
          },
        ],
        patterns: [
          {
            regex: '^\\.\\./\\.\\./',
            message:
              'Use alias imports (@/dir/) instead of deep relative imports (../../). Single-level (../) is allowed for colocated files.',
          },
        ],
      },
    ],
    // Both are correctness, so the category would switch them on. They force
    // full module resolution and are the single biggest oxlint slowdown; we
    // only want import/first from that plugin.
    'import/default': 'off',
    'import/namespace': 'off',
    'react/no-array-index-key': 'warn',
    'react/jsx-no-target-blank': 'error',
    'react/no-unstable-nested-components': 'error',
    'oxc/no-accumulating-spread': 'warn',
    'promise/no-return-in-finally': 'error',

    // --- perf category, hand-picked ------------------------------------------
    // Biome had no equivalent for any of these. The category as a whole is not
    // enabled: its `no-await-in-loop` fires 49 times on scripts that are
    // sequential on purpose. These three are the ones that pay for themselves;
    // oxc/no-map-spread is deliberately not among them, since it wants
    // Object.assign in place of a plain per-item spread, which reads worse for
    // no measurable gain here.
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-array-find': 'error',
    'react/no-object-type-as-default-prop': 'error',

    // --- Consciously disabled during the Biome -> Oxc migration ---------------
    // Under Biome these were nursery/warn, which never failed a build. `lint`
    // now runs with --max-warnings=0, so leaving them on would turn pre-existing
    // findings into hard failures. Off preserves today's effective behaviour.
    // 11 pre-existing sites (regex literals in scripts + tests).
    'eslint/prefer-named-capture-group': 'off',
    // Off on purpose, and it should stay off: the fix this rule asks for is
    // useMemo around context values, which this repo forbids because the React
    // Compiler already memoises them (see AGENTS.md). Enabling it would mean
    // hand-writing memoisation the compiler undoes.
    'react/jsx-no-constructed-context-values': 'off',

    // --- Type-aware rules (only active under `bun run lint:types`) -----------
    'typescript/consistent-type-exports': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-misused-promises': 'error',

    // Biome's useNullishCoalescing was a nursery warn and never failed a build.
    // 27 pre-existing `||` sites; converting them changes falsy-vs-nullish
    // behaviour case by case, so it is a follow-up, not a migration step.
    'typescript/prefer-nullish-coalescing': 'off',

    // `--type-aware` switches on every type-aware rule in the correctness
    // category, not just the ones enabled above. These extras are new signal
    // that no one has triaged yet; each needs its own pass, and leaving them on
    // would fail `bun run check` on day one. Turned off deliberately, to be
    // re-enabled one at a time.
    'typescript/await-thenable': 'off',
    'typescript/restrict-template-expressions': 'off',
    'typescript/no-misused-spread': 'off',
    'typescript/no-base-to-string': 'off',
    'typescript/unbound-method': 'off',
    'typescript/no-duplicate-type-constituents': 'off',
  },

  overrides: [
    {
      // Storybook CSF `render`/`decorator` functions are anonymous arrow
      // functions that legitimately call hooks. rules-of-hooks cannot see them
      // as components because they are neither PascalCase nor `use`-prefixed.
      files: ['**/*.stories.tsx', '.storybook/**'],
      rules: {
        'react/rules-of-hooks': 'off',
      },
    },
    {
      // The `components` prop of @portabletext/react is a map of serializer
      // functions -- defining them inline is the library's documented API, not
      // an accidental component-in-render.
      files: ['lib/integrations/sanity/components/rich-text.tsx'],
      rules: {
        'react/no-unstable-nested-components': 'off',
      },
    },
    {
      files: ['**/*.tsx', '**/*.jsx'],
      rules: {
        'react/jsx-key': 'error',
        'jsx-a11y/anchor-is-valid': 'error',
        'jsx-a11y/click-events-have-key-events': 'error',
        'jsx-a11y/mouse-events-have-key-events': 'error',
      },
    },
    {
      files: ['**/*.ts', '**/*.tsx'],
      rules: {
        'typescript/consistent-type-imports': [
          'error',
          {
            prefer: 'type-imports',
            fixStyle: 'separate-type-imports',
            disallowTypeAnnotations: true,
          },
        ],
        'typescript/array-type': [
          'error',
          { default: 'array', readonly: 'array' },
        ],
        'eslint/no-undef': 'off',
      },
    },
    {
      // The Link component must render a real anchor.
      files: ['components/ui/link/**'],
      rules: {
        'react/forbid-elements': 'off',
      },
    },
    {
      files: [
        'e2e/**',
        '**/*.test.ts',
        '**/*.test.tsx',
        'lib/scripts/**',
        '.storybook/**',
      ],
      rules: {
        'eslint/no-restricted-imports': 'off',
        'unicorn/filename-case': 'off',
        'react/forbid-elements': 'off',
      },
    },
    {
      // Test and storybook casts are fixture plumbing; a SAFETY: justification
      // per cast would be noise, and typeof probing is routine in assertions.
      files: ['e2e/**', '**/*.test.ts', '**/*.test.tsx', '.storybook/**'],
      rules: {
        'anti-slop/require-safety-comment-for-type-assertion': 'off',
        'anti-slop/no-runtime-typeof': 'off',
      },
    },
    {
      // CLI tooling probes CLI/env/JSON values with typeof by nature; there
      // is no upstream I/O boundary to push the parse to.
      files: ['lib/scripts/**', 'lib/styles/scripts/**'],
      rules: {
        'anti-slop/no-runtime-typeof': 'off',
      },
    },
    {
      // runFormAction wraps next/headers and the Turnstile validator with no
      // injectable seam; removing mock.module here would mean changing
      // form-action's public API just to satisfy the rule.
      files: ['lib/utils/form-action.test.ts'],
      rules: {
        'anti-slop/no-module-mocking': 'off',
      },
    },
  ],
})
