import * as config from '../config'
import { generateBase } from './generate-base'
import { generateScale } from './generate-scale'

const base = generateBase(config)

const scale = generateScale()

const banner = `/*
 * THIS FILE IS GENERATED BY tailwind.mjs
 * DO NOT EDIT IT DIRECTLY.
 */`

const parts = [banner, base, scale]

await Bun.write('./styles/css/tailwind.css', parts.join('\n\n'))
console.log(
  Bun.color('green', 'ansi'),
  '✓',
  Bun.color('black', 'ansi'),
  'Style config generated successfully'
)
