import * as config from '../config'
import { generateRoot } from './generate-root'
import { generateScale } from './generate-scale'
import { generateTailwind } from './generate-tailwind'

const tailwind = generateTailwind(config)
const root = generateRoot(config)
const scale = generateScale()

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

const tailwindcss = [banner, tailwind, scale]
const rootcss = [banner, root]

await Bun.write('./styles/css/tailwind.css', tailwindcss.join('\n\n'))
await Bun.write('./styles/css/root.css', rootcss.join('\n\n'))

console.log(
  Bun.color('green', 'ansi'),
  '✓',
  Bun.color('black', 'ansi'),
  'Style config generated successfully'
)
