import { writeFile } from 'node:fs/promises'
import * as config from '../config.mjs'
import { generateBase } from './generate-base.mjs'
import { generateFluid } from './generate-fluid.mjs'

const base = generateBase({
  breakpoints: config.breakpoints,
  fontFamilies: config.fontFamilies,
  layout: config.layout,
  screens: config.screens,
  themes: config.themes,
  typeStyles: config.typeStyles,
})

const fluid = generateFluid()

const banner = `/*
 * THIS FILE IS GENERATED BY tailwind.mjs
 * DO NOT EDIT IT DIRECTLY.
 */`

const parts = [banner, base, fluid]

await writeFile('./styles/tailwind.css', parts.join('\n\n'), 'utf-8')
