import { writeFile } from 'node:fs/promises'
import * as styles from '../config.mjs'
import { generateBase } from './generate-base.mjs'
import { generateFluid } from './generate-fluid.mjs'

const layout = { ...styles.config }
// biome-ignore lint/performance/noDelete: fuck off
delete layout.themes

const base = generateBase({
  breakpoints: styles.breakpoints,
  layout,
  screens: styles.screens,
  themes: styles.themes,
})

const fluid = generateFluid()

const banner = `/*
 * THIS FILE IS GENERATED BY tailwind.mjs
 * DO NOT EDIT IT DIRECTLY.
 */`

const parts = [banner, base, fluid]

await writeFile('./styles/tailwind.css', parts.join('\n\n'), 'utf-8')
